version: "3.9"

services:

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./config/dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./config/.env
    volumes:
      - ./source:/app/source
    depends_on:
      - elasticsearch

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.10.4
    restart: always
    ports:
      - "9200:9200"
    env_file:
      - ./config/.env
